language: php

php:
 - 5.3
 - 5.4
 - 5.5
 - 5.6
 - hhvm
 - hhvm-nightly

matrix:
    allow_failures:
     - php: hhvm
     - php: hhvm-nightly

before_script:
 - composer install --prefer-source --dev

script:
 - php vendor/bin/phpunit -v --coverage-clover ./build/coverage/clover.xml

after_script:
 - php vendor/bin/coveralls -v
